#!/usr/bin/env python
# Copyright 2011 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

from paste import httpserver

from u1db import (
    __version__ as _u1db_version,
    )
from u1db.remote import (
    http_app,
    server_state,
    )


def main(args):
    import argparse
    p = argparse.ArgumentParser(usage='%(prog)s [options]',
        description='Run the U1DB server')
    p.add_argument('--version', action='version', version=_u1db_version)
    p.add_argument('--verbose', action='store_true', help='be chatty')
    p.add_argument('--port', '-p', default=0, metavar='PORT', type=int,
        help='Bind to this port when serving.')

    args = p.parse_args(args)

    state = server_state.ServerState()
    state.set_workingdir('.')
    application = http_app.HTTPApp(state)
    server = httpserver.WSGIServer(application, ('', args.port),
                                   httpserver.WSGIHandler)
    sys.stdout.write('listening on port: %s\n' % (server.server_address[1],))
    sys.stdout.flush()
    server.serve_forever()


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))


# vim: ft=python
