#!/usr/bin/env python
# Copyright 2011 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

import u1db


def main(args):
    import argparse
    p = argparse.ArgumentParser(usage='%(prog)s [options]',
        description='Run the U1DB server')
    p.add_argument('--version', action='version', version=u1db.__version__)
    p.add_argument('--verbose', action='store_true', help='be chatty')
    p.add_argument('--database', '-d', default=None, metavar='DB',
        help='Use this file as the database')
    p.add_argument('--port', '-p', default=None, metavar='PORT',
        help='Bind to this port when serving.')

    args = p.parse_args(args)


if __name__ == '__main__':
    import sys
    main(sys.argv[1:])


# vim: ft=python
